import 'package:curve_design/colors.dart';
import 'package:curve_design/widgets/single_item.dart';
import 'package:flutter/material.dart';

const List<Widget> items = [
  SingleItem(
    imagePath: 'assets/calendar.png',
    backgroundColor: AppColors.lightPinkColor,
    title: '3D icons project',
    progress: .8,
    estimatedTimeInDays: 5,
  ),
  SingleItem(
    imagePath: 'assets/dash.png',
    backgroundColor: AppColors.lightBlueColor,
    title: 'UI design for Opaper',
    progress: .4,
    estimatedTimeInDays: 10,
    imagePadding: const EdgeInsets.all(4.0),
    imageHeight: 50.0,
  ),
  SingleItem(
    imagePath: 'assets/dash.png',
    backgroundColor: AppColors.lightBlueColor,
    title: 'UI design for Opaper',
    progress: .8,
    estimatedTimeInDays: 10,
    imagePadding: const EdgeInsets.all(4.0),
    imageHeight: 50.0,
  ),
  SingleItem(
    imagePath: 'assets/dash.png',
    backgroundColor: AppColors.lightBlueColor,
    title: 'UI design for Opaper',
    progress: .7,
    estimatedTimeInDays: 10,
    imagePadding: const EdgeInsets.all(4.0),
    imageHeight: 50.0,
  ),
  SingleItem(
    imagePath: 'assets/dash.png',
    backgroundColor: AppColors.lightBlueColor,
    title: 'UI design for Opaper',
    progress: .9,
    estimatedTimeInDays: 10,
    imagePadding: const EdgeInsets.all(4.0),
    imageHeight: 50.0,
  ),
  SingleItem(
    imagePath: 'assets/dash.png',
    backgroundColor: AppColors.lightBlueColor,
    title: 'UI design for Opaper',
    progress: .9,
    estimatedTimeInDays: 10,
    imagePadding: const EdgeInsets.all(4.0),
    imageHeight: 50.0,
  ),
  SingleItem(
    imagePath: 'assets/dash.png',
    backgroundColor: AppColors.lightBlueColor,
    title: 'UI design for Opaper',
    progress: .65,
    estimatedTimeInDays: 10,
    imagePadding: const EdgeInsets.all(4.0),
    imageHeight: 50.0,
  ),
  SingleItem(
    imagePath: 'assets/dash.png',
    backgroundColor: AppColors.lightBlueColor,
    title: 'UI design for Opaper',
    progress: 1,
    estimatedTimeInDays: 10,
    imagePadding: const EdgeInsets.all(4.0),
    imageHeight: 50.0,
  ),
  SingleItem(
    imagePath: 'assets/dash.png',
    backgroundColor: AppColors.lightBlueColor,
    title: 'UI design for Opaper',
    progress: .2,
    estimatedTimeInDays: 10,
    imagePadding: const EdgeInsets.all(4.0),
    imageHeight: 50.0,
  ),
];